### PR TITLE
Rearranged sorting and returned self

### PR DESCRIPTION
**Pull request by dotjersh**
- Removed the sort option in Int, and added `increasing()`
- Returned self at the end of every function to allow us to do: `myList.int().increasing()`

### CODE REVIEW

**Comment by bendacoder** [comment]
Good thinking with the `return self`. I don't think we should have duplicate of the sort function since we are already inheriting from the list class.

**Comment by dotjersh** [comment]
Ooooh, using the sort from the list class works. Didn't catch that. I removed the `increasing()` function.

**Comment by bendacoder** [comment]
Looks good (I could even say 'tov me`od'!). Merging.

**Comment by dotjersh** [comment]
What's up?

**Comment by bendacoder** [comment]
Nothing, organizing the contributors for the pull request.

**Pull request merged**
